### ISSUE TITLE
Cropped images in wikisource introduces full image also in PDF file 

### ISSUE THREAD

**Issue by arjunaraoc** [wsexport/tool#103]
The PDF rendered from page https://te.wikisource.org/wiki/%E0%B0%AE%E0%B0%BE%E0%B0%B0%E0%B0%BF%E0%B0%B7%E0%B0%B8%E0%B1%8D%E2%80%8C%E0%B0%B2%E0%B1%8B_%E0%B0%A4%E0%B1%86%E0%B0%B2%E0%B1%81%E0%B0%97%E0%B1%81_%E0%B0%A4%E0%B1%87%E0%B0%9C%E0%B0%82  has lot of pictures in the last chapter, which are cropped and sometimes rotated 90 degrees using Template:CSS image crop.   While the epub renders such images well, pdf renders them but  also adds original image page in full,
![image crop add original page apart from cropped image](https://cloud.githubusercontent.com/assets/524249/14709593/13272206-07ef-11e6-8f34-9bcca3c3c9ef.PNG)

**Comment by zdzis** [comment]
the PDF is generated by converting the epub in Calibre. 
because you are using for cropping the image css styles:
```
<div style="position:relative; width:297px; height:212px; overflow:hidden;">
<div style="position:relative; top:-30px; left:-90px; -webkit-transform:rotate(0deg); -moz-transform:rotate(0deg); -o-transform:rotate(0deg); transform:rotate(0deg);"....
```
and the pdf does not "support" inter alia `overflow:hidden`... Calibre is doing its best... and the effect you already know :))  the only way out is to not use CSS for cropping, but placed on Common pictures already cropped...

next time, please, install Calibre yourself and see how you get the result of the transformation from epub into pdf (and whether the problem does not lie in the code of ws pages) before you submit a wsExport issue

Z.

**Comment by arjunaraoc** [comment]
Thanks for the explanation and suggestion for submitting future bugs

**Comment by arjunaraoc** [comment]
The problem was not present when converted using Calibre 2.54

**Comment by zdzis** [comment]
I have 2.37 and "the problem" still occurs, I have also converted the [ePub from మారిషస్‌లో తెలుగు తేజం](https://tools.wmflabs.org/wsexport/tool/book.php?lang=te&format=epub-3&page=%E0%B0%AE%E0%B0%BE%E0%B0%B0%E0%B0%BF%E0%B0%B7%E0%B0%B8%E0%B1%8D%E2%80%8C%E0%B0%B2%E0%B1%8B+%E0%B0%A4%E0%B1%86%E0%B0%B2%E0%B1%81%E0%B0%97%E0%B1%81+%E0%B0%A4%E0%B1%87%E0%B0%9C%E0%B0%82) into pdf on [http://www.ebookconverter.net/](http://www.ebookconverter.net/) (they are using Calibre 2.54) and I received also the same effect as in the ![picture](https://cloud.githubusercontent.com/assets/524249/14709593/13272206-07ef-11e6-8f34-9bcca3c3c9ef.PNG)

**Comment by balajijagadesh** [comment]
@zdzis 

Hi.. I am too facing the same problem using the image crop template. I read that the problem is not from the tool side, but from the template. 

But is there any work around which can be tried. Like adding some codes to mediawiki:Epub.css so that the image crop style css is also included. Or some other page can be created?

I feel this is a real issue which needs attending. 

Kindly appealing for think about this issue.
