### ISSUE TITLE
<ref>...</ref>

### ISSUE THREAD

**Issue by anton-petrunin** [wsexport/tool#132]
The comments in "<ref>...</ref>" do not work properly in EPUB.

Can it be fixed? 

Or what is the right way to write comments in wikisourse?

**Comment by Tpt** [comment]
Thank you for this bug report! Not sure to understand what do you mean by 'comments in "..." '. Could you give me an example, please?

**Comment by anton-petrunin** [comment]
For "something <ref>something else</ref>" in the text, the ebook reader is see "something [number]", but the link is not usable. (I use pocketbook, but likely it does not matter)

**Comment by Tpt** [comment]
Ok, I see. There is sometime problems with very big wiki pages that have to be split in two in order to be openable in old ePub readers. When it the case footnotes are broken in the first part of the wiki page. Do you think it is what is happening in you case? Could you give me a link to the wiki page you are trying to export?

**Comment by anton-petrunin** [comment]
Suddenly it started to work --- maybe it did not work before because of forgotten `<references/>`.
Sorry for taking your time.

**Comment by Tpt** [comment]
It is fine :-) Nice to see a new Wikisource contributor!
