### ISSUE TITLE
letter-spacing

### ISSUE THREAD

**Issue by anton-petrunin** [wsexport/tool#135]
Letter spacing is commonly used to emphasize text in Russian.
We use `Template:Razr` which is simply `<span style="letter-spacing: 0.2em">something here</span>`.

If extracted to epub or pdf, the letter spacing disappears. 

Is it possible to fix? (I am ready to change the template if necessary.)

Here is one [example](https://ru.wikisource.org/wiki/%D0%91%D1%80%D0%BE%D0%B4%D1%8F%D0%B3%D0%B8_%D0%B4%D1%83%D1%85%D0%BE%D0%B2%D0%BD%D0%BE%D0%B3%D0%BE_%D1%87%D0%B8%D0%BD%D0%B0_(%D0%A5%D0%B0%D1%80%D0%B0%D0%BA%D1%82%D0%B5%D1%80%D0%BD%D0%BE%D0%B5_%D1%8F%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_%D1%86%D0%B5%D1%80%D0%BA%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D0%B6%D0%B8%D0%B7%D0%BD%D0%B8_XVIII_%D0%B2%D0%B5%D0%BA%D0%B0)).

**Comment by ousia** [comment]
You only have to fix it in the CSS. I don’t think it is a good idea to modify the HTML source.

``` css
em:lang(ru) {
    font-style: normal;
    letter-spacing: 0.2em;
}
```

I don’t know how PDF documents are actually generated, but a similar approach should be possible.

**Comment by samwilson** [comment]
I'm not sure it's that simple. If the CSS is already in the wikitext, then it'll be in the epub as-is. For example, the following is from the generated epub of the above example:

    <p>В марте 743 года из Святогорского монастыря «бежал поп
    <span style="letter-spacing: 0.2em; word-spacing: -0.2em;">Андрей Шапкин</span>,
    содержавшийся в монастыре по некоторому секретному делу, — лица белого и громогласен».

Could the display discrepancy be to do with the software or device that's displaying the epub?

**Comment by ousia** [comment]
@samwilson, I think it would be better to fix the markup in the HTML source. A bot could do that, couldn’t it?

**Comment by anton-petrunin** [comment]
sure, but what should be instead of `{{razr|something here}}`?

**Comment by samwilson** [comment]
> I think it would be better to fix the markup in the HTML source.

Maybe I'm not understanding, but it seems that there's nothing to fix in the source. The problem is that the reduced letter-spacing isn't displaying as desired by some epub readers.

Part of the example above looks like this in my web browser:

![On wiki](https://user-images.githubusercontent.com/213655/54002265-ee3f6300-4188-11e9-93ed-583c14255ad7.png)

And this in the Calibre viewer:

![Calibre](https://user-images.githubusercontent.com/213655/54002264-ee3f6300-4188-11e9-97a4-af49204d4990.png)

So I assume it's the ereader's rendering that's failing.

**Comment by anton-petrunin** [comment]
You are right --- the problem with my device (PocketBook 626).
Thank you.

**Comment by ousia** [comment]
> Maybe I'm not understanding, but it seems that there's nothing to fix in the source. The problem is that the reduced letter-spacing isn't displaying as desired by some epub readers.

@samwilson,

I agree, the source isn’t broken.

If it were tagged as `<em>`, it would be easy to change the CSS code in order to have italics, at least.

It would also allow to have right letter-spacing on other devices (or even in this one, once it would be fixed).

It is just a different approach. I don’t think it is an improvement to hard-code properties in XHTML sources.

**Comment by samwilson** [comment]
@ousia that's a good point about using `<em>`, but I'm not sure it'd help because I assume that people don't want letter-spacing *and* italics at the same time (on devices that support both) and there doesn't seem to be a way of detecting whether letter-spacing is available.

But certainly the [{{razr}} template](https://ru.wikisource.org/wiki/%D0%A8%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD:Razr) on Russian Wikisource could be changed to use an `em` element instead of a `span`. It'd probably have to remove the italics, but could maybe add them back via [MediaWiki:Epub.css](https://ru.wikisource.org/wiki/MediaWiki:Epub.css).

Whether the letter-spacing is applied within a style attribute or as an epub-wide stylesheet is irrelevant, it looks like. For example, the following code rendered on a Kobo:

```
* normal <span style="letter-spacing:0.2em">attribute-spaced letters in a span</span> normal again
* normal <em style="letter-spacing:0.2em">attribute-spaced letters in an em</em> normal again
* normal <span class="spaced">stylesheet-spaced letters in a span</span> normal again
* normal <em class="spaced">stylesheet-spaced letters in an em</em> normal again
```

(With `em.spaced, span.spaced { letter-spacing:0.2em; }` in the stylesheet.)

![leter-spacing](https://user-images.githubusercontent.com/213655/56881041-af939e00-6a91-11e9-8b75-64108f76c8ac.jpg)

**Comment by samwilson** [comment]
I don't think there's anything else here that WSExport needs to do. (Please reopen this or report a new issue if I'm wrong.)
