### ISSUE TITLE
Strange file structure in the root of EPUB 2.0

### ISSUE THREAD

**Issue by pbtsrc** [wsexport/tool#243]
EPUB 2.0:

META-INF 
OPS 
content.opf 
cover_image.jpg 
mimetype 
page_styles.css 
stylesheet.css 
titlepage.xhtml 
toc.ncx

EPUB 3.0:

META-INF 
OPS 
mimetype

**Comment by samwilson** [comment]
Thanks for reporting this. Could you say more about what's strange about this, or what issues you're experiencing?

Note that Epub 2 files are produced by generating an Epub 3 file and then using Calibre to convert it to Epub 2, so I suspect that any errors with that process are due to Calibre's handling of it.

**Comment by pbtsrc** [comment]
No, thankfully I don't see any issues with those files on all my readers. 
I just found that Epub 2 files I have downloaded last year have the same file structure as Epub 3 files. And the new ones are different. So I thought that was some regression or something.

**Comment by samwilson** [comment]
Thanks for being so thorough!

But yeah, the change is intentional, and I'm glad it's not caused any issues for you.

Closing this for now. If you do find any problems with Epub 2, feel free to open more issues (on Phabricator though, where we're moving all issue-tracking to, so it's all in one place).
