### ISSUE TITLE
Histoire socialiste/Consulat & Empire export error

### ISSUE THREAD

**Issue by JeanVALJEAN31** [wsexport/tool#31]
Cannot export to epub the book from Jean Jaures:
Consulat & Empire , from his "Histoire Socialist".

Due to & in the wikisource page title?

**Comment by jmatazzoni** [comment]
Did this get fixed? Is it really/still the case that any book with an ampersand (&) in chapter titles crashes export? Or do I misunderstand?

**Comment by Tpt** [comment]
I could still reproduce the error: https://tools.wmflabs.org/wsexport/tool/book.php?lang=fr&page=Histoire+socialiste%2FConsulat+%26+Empire

**Comment by Tpt** [comment]
I could still reproduce the error with "&": https://tools.wmflabs.org/wsexport/tool/book.php?lang=fr&page=Histoire+socialiste%2FConsulat+%26+Empire

I do not manage to reproduce the problem with "é" from the second comment. I believe it was a problem somewhere else that raised the second comment because I never encountered problems with not ASCII characters.

**Comment by samwilson** [comment]
It looks like the issue with the ampersand is fixed now, is that correct? The [above work](https://fr.wikisource.org/wiki/Histoire_socialiste/Consulat_&_Empire) now redirects to `Histoire socialiste/Consulat et Empire`, but exporting the old name doesn't give an error (the only thing in the epub is the redirect page, but that's a [separate issue](https://phabricator.wikimedia.org/T259064)).

**Comment by samwilson** [comment]
This is no longer an issue. (If it is, please open a new issue on Phabricator.)
