### ISSUE TITLE
Cache produced files

### ISSUE THREAD

**Issue by nemobis** [wsexport/tool#38]
It would be nice if you cached the files you produce for at least some days, as [[mw:OCG]] / Collection does. Not only that could save some processing time, but most importantly we could serve books faster to our users.
Currently, the waiting times are often rather extreme...

**Comment by Aubreymcfato** [comment]
This is a great idea: the ideal system, to me, would be the tool to "know" when a book has been modified (eg. a page proofread or corrected) so that the cache can be override.

**Comment by jberkel** [comment]
Right now the slowest part of the book generation is fetching the credit information for all the pages because it needs to go through all of the individual source pages. If this could be cached it would already speed things up considerably.

A more general caching solution would be as @Aubreymcfato suggested to keep generated books with the timestamp of the most recent page, and then query the API for more recent modifications of pages. If none exist, serve the cached version.

**Comment by samwilson** [comment]
At the moment we query https://tools.wmflabs.org/phetools/credits.py to get the names of contributors. That [script](https://github.com/phil-el/phetools/blob/master/history_credit/get_credit.py) queries the database directly. We send batches of 50 page titles at once; this could probably be increased, to reduce the number of requests.

I think this script is used rather than the API, in order to save an API call — because you'd first have to request the contributors for a given set of pages, and then find the groups of those users (so we can sort bots to the bottom).

As for determining a 'last modified' date for a work... does anyone have any ideas about that? It seems that we'd need to traverse the whole book (all subpages and Page NS pages) to see if any were newer than when we saw them last, and we would still have to parse each page as we go in order to find the links to the other pages in the book. By the end of that, we've done the whole book and so knowing that it's the same as last time doesn't really help. :)

The simplest thing might just be to cache the entire final generated file for an hour (and add a new `nocache` parameter that can be used while debugging a book).

**Comment by jberkel** [comment]
oh, completely forgot about this ticket… 

@samwilson agreed, we can give this a try, in practice the books probably don't change much after proofreading.  and it's very expensive to get the last modified date, and it's not just content pages but in theory also templates and modules that influence the  book rendering. it's really a whole graph of dependencies.

**Comment by samwilson** [comment]
Gosh, yeah I forgot about the chain of dependent pages! Too hard. :-)

Okay then, let's:

1. Increase the number of pages in each batch of credits-getting; and
2. Store every generated file for a minumum of 1 hour, with a `nocache` parameter permitted (which would also be an additional form field, I guess).

**Comment by jberkel** [comment]
To make things really fast we could also directly connect to the database to get the credit information. I'm not sure what the query actually does, and can't find the sources of phetools at the moment, it's not listed on toolforge.

**Comment by samwilson** [comment]
I was thinking that too. It'd go well with [this idea](https://github.com/wsexport/tool/issues/168#issuecomment-490791790) of storing the logs in the tools' database (I mean, both would require wsexport to have a MariaDB database connection).

The source for the phetools script is [here](https://github.com/phil-el/phetools/blob/master/history_credit/get_credit.py) and it queries both the Wikisource of the book and Commons for the contributors of images. From a cursory look, I think the queries could be made more efficient, and anyway doing them directly in wsexport is going to be faster than the extra HTTP requests to get their results.

**Comment by jberkel** [comment]
Just had a quick look at the credits.py: I don't understand why we need to pass in all the pages when the service could just take a `book` parameter and  compute everything in one single query?

It does accept a book name and there is some logic to get the pages for a book title ([get_credit.py#L81](https://github.com/phil-el/phetools/blob/07ea814d8b628b2708b3a3547f63ae3c3e332e7e/history_credit/get_credit.py#L81)) but it doesn't seem to work properly:

```
curl 'https://tools.wmflabs.org/phetools/credits.py?lang=en&cmd=history&book=Una_and_the_Lion&format=json'
```

returns nothing.

**Comment by samwilson** [comment]
Yeah, I guess there's a bug with the `book` parameter. Passing the pages in works, e.g.

    curl 'https://tools.wmflabs.org/phetools/credits.py?lang=en&cmd=histy&page=Una_and_the_Lion&format=json'

I think the reason for passing pages (include Page NS ones) is that then only contributors to the actual pages used in the book are listed. We don't currently make the assumption that *every* subpage is part of the exported book, nor that every Page NS page of an Index is transcluded. I do wonder if actually we could make these assumptions, and err on the side of including too many contributors' names, because doing that might be a much more efficient query.

I might look at adding credits-querying to the [wikisource/api](https://packagist.org/packages/wikisource/api) PHP library, then using that in wsexport.

**Comment by jberkel** [comment]
Moving the credit logic into wsexport is an option but I think it would be preferable to have an external service handle this efficiently. 

I don't understand how the PHP library would make things faster, as you'd still have to make many separate queries?

**Comment by samwilson** [comment]
The topics here are now being tracked on Phabricator:
* Caching of generated books: https://phabricator.wikimedia.org/T222936
* Remove dependency on credits.py: https://phabricator.wikimedia.org/T257886
